import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.purple[50],
  },
  scrollView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(28),
  },
  intro: {
    alignItems: 'center',
    paddingTop: verticalScale(20),
    paddingBottom: verticalScale(16),
  },
  logoFrame: {
    width: scale(64),
    height: scale(64),
    borderRadius: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[200],
    marginBottom: verticalScale(12),
    position: 'relative',
  },
  verifiedBadge: {
    position: 'absolute',
    top: -scale(3),
    right: -scale(3),
    width: scale(20),
    height: scale(20),
    borderRadius: scale(10),
    backgroundColor: colors.purple[600],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: scale(2),
    borderColor: colors.purple[50],
  },
  heading: {
    fontFamily: fonts.Bold,
    color: colors.black[250],
    fontSize: fontSize[24],
    lineHeight: verticalScale(30),
    fontWeight: '700',
    textAlign: 'center',
  },
  subheading: {
    maxWidth: scale(310),
    marginTop: verticalScale(4),
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
    textAlign: 'center',
  },
  card: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: verticalScale(16),
    borderWidth: scale(1),
    borderColor: colors.purple[200],
    shadowColor: colors.black[250],
    shadowOffset: { width: scale(0), height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: scale(6),
    elevation: 2,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(4),
  },
  labelRequiredText: {
    fontFamily: fonts.Regular,
    fontSize: fontSize[12],
    color: colors.grey[700],
  },
  matchBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  matchText: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontSize: fontSize[12],
    fontWeight: '600',
  },
  strengthSection: {
    marginTop: verticalScale(2),
    marginBottom: verticalScale(14),
    padding: scale(12),
    borderRadius: scale(12),
    backgroundColor: colors.purple[50],
    gap: verticalScale(8),
  },
  strengthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  strengthTitle: {
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
    fontSize: fontSize[12],
    fontWeight: '600',
  },
  strengthLabel: {
    fontFamily: fonts.Bold,
    fontSize: fontSize[12],
    fontWeight: '700',
  },
  barsContainer: {
    flexDirection: 'row',
    gap: scale(6),
  },
  strengthBar: {
    flex: 1,
    height: verticalScale(5),
    borderRadius: scale(3),
    backgroundColor: colors.purple[200],
  },
  reqList: {
    gap: verticalScale(4),
    marginTop: verticalScale(4),
  },
  reqItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  reqText: {
    fontFamily: fonts.Regular,
    fontSize: fontSize[12],
    color: colors.grey[700],
  },
  reqTextActive: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontWeight: '600',
  },
  securityTipCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
    padding: scale(12),
    borderRadius: scale(12),
    backgroundColor: colors.purple[100],
    marginTop: verticalScale(4),
  },
  securityTipText: {
    flex: 1,
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[12],
    lineHeight: verticalScale(16),
  },
  actions: {
    gap: verticalScale(8),
  },
  submitButton: {
    height: verticalScale(48),
  },
  buttonArrow: {
    fontFamily: fonts.Regular,
    color: colors.white[100],
    fontSize: fontSize[18],
  },
  cancelButton: {
    minHeight: verticalScale(44),
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
    fontSize: fontSize[14],
    fontWeight: '600',
  },
  flexSpacer: {
    flex: 1,
  },
});
