import { StyleSheet } from 'react-native';
import { colors, fonts } from '../../../../constants';
import { fontSize, sWidth, scale, verticalScale } from '../../../../constants/metrics';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white[100],
  },
  headerContainer: {
    borderBottomWidth: 1,
    borderBottomColor: colors.grey[100] ?? '#EEEEEE',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: scale(16),
    paddingBottom: verticalScale(40),
    gap: scale(16),
  },
  heroCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: scale(4),
    elevation: 3,
    position: 'relative',
    overflow: 'hidden',
  },
  heroGradientBg: {
    position: 'absolute',
    right: scale(-40),
    top: verticalScale(-40),
    width: scale(140),
    height: verticalScale(140),
    borderRadius: scale(70),
    backgroundColor: colors.purple[100], // gradient approximation
    opacity: 0.6,
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(16),
  },
  avatarContainer: {
    position: 'relative',
    width: scale(80),
    height: verticalScale(80),
  },
  avatarGradient: {
    width: '100%',
    height: '100%',
    borderRadius: scale(40),
    backgroundColor: colors.purple[500],
    padding: scale(4),
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: scale(36),
    backgroundColor: colors.grey[200],
  },
  onlineDot: {
    position: 'absolute',
    top: verticalScale(0),
    right: scale(0),
    width: scale(16),
    height: verticalScale(16),
    borderRadius: scale(8),
    backgroundColor: colors.green[500],
    borderWidth: scale(2),
    borderColor: colors.white[100],
  },
  cameraButton: {
    position: 'absolute',
    bottom: verticalScale(0),
    right: scale(0),
    width: scale(28),
    height: verticalScale(28),
    borderRadius: scale(14),
    backgroundColor: colors.purple[700],
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: scale(1),
    elevation: 2,
  },
  heroTextContainer: {
    flex: 1,
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E0E7FF',
    alignSelf: 'flex-start',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: scale(100),
    marginBottom: verticalScale(4),
  },
  verifiedText: {
    fontSize: fontSize[10],
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    marginLeft: scale(4),
  },
  providerName: {
    fontSize: fontSize[22],
    fontFamily: fonts.Bold,
    color: colors.black[500],
  },
  businessName: {
    fontSize: fontSize[13],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: scale(1),
    alignSelf: 'flex-start',
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: scale(100),
    marginTop: verticalScale(8),
  },
  statusDot: {
    width: scale(8),
    height: verticalScale(8),
    borderRadius: scale(4),
    backgroundColor: colors.green[500],
    marginRight: scale(6),
  },
  statusText: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.green[700],
  },
  availabilityCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    borderWidth: scale(1),
    borderColor: colors.grey[200] ?? '#EEEEEE',
  },
  availabilityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: verticalScale(12),
  },
  availabilityHeaderLeft: {
    flexDirection: 'row',
    gap: scale(8),
    flex: 1,
  },
  availabilityIconBg: {
    width: scale(32),
    height: verticalScale(32),
    borderRadius: scale(8),
    backgroundColor: '#ECFDF5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  availabilityTitle: {
    fontSize: fontSize[16],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
  },
  availabilitySub: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[700],
  },
  availabilityStatusLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
    borderWidth: scale(1),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: scale(100),
  },
  availabilityStatusLabelOffline: {
    backgroundColor: colors.grey[100],
    borderColor: colors.grey[200],
  },
  availabilityStatusText: {
    fontSize: fontSize[12],
    fontFamily: fonts.SemiBold,
    color: colors.green[700],
  },
  availabilityStatusTextOffline: {
    color: colors.grey[600],
  },
  availabilityDesc: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
    marginBottom: verticalScale(16),
    lineHeight: verticalScale(18),
  },
  offlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: verticalScale(44),
    borderRadius: scale(12),
    backgroundColor: colors.grey[100],
    borderWidth: scale(1),
    borderColor: colors.grey[200],
  },
  offlineBtnText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
    marginLeft: scale(8),
  },
  insightsCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    borderWidth: scale(1),
    borderColor: colors.grey[200] ?? '#EEEEEE',
  },
  insightsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: verticalScale(12),
    borderBottomWidth: 1,
    borderBottomColor: colors.grey[100],
    marginBottom: verticalScale(12),
  },
  insightsTitle: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.grey[600],
    textTransform: 'uppercase',
    letterSpacing: scale(0.5),
  },
  insightsLink: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
  },
  insightsGrid: {
    flexDirection: 'row',
    gap: scale(12),
  },
  insightBox: {
    flex: 1,
    backgroundColor: colors.grey[100] ?? '#F8F9FA',
    borderRadius: scale(12),
    padding: scale(12),
  },
  insightBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
    marginBottom: verticalScale(4),
  },
  insightBoxTitle: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
  },
  insightValue: {
    fontSize: fontSize[18],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
  },
  insightSub: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: verticalScale(2),
    gap: scale(2),
  },
  insightSubText: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.green[700], // For earnings
  },
  insightSubTextGrey: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
  },
  profileInfoCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
  },
  profileInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(16),
  },
  profileInfoTitle: {
    fontSize: fontSize[16],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  editBtnText: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
  },
  infoList: {
    gap: scale(8),
    marginBottom: verticalScale(16),
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
    padding: scale(8),
    backgroundColor: colors.grey[100] ?? '#F8F9FA',
    borderRadius: scale(12),
  },
  infoIconBg: {
    width: scale(36),
    height: verticalScale(36),
    borderRadius: scale(8),
    backgroundColor: colors.white[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoTextContainer: {
    flex: 1,
  },
  infoLabel: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
  },
  infoValue: {
    fontSize: fontSize[14],
    fontFamily: fonts.Medium,
    color: colors.black[500],
  },
  bioContainer: {
    backgroundColor: colors.grey[100] ?? '#F8F9FA',
    borderRadius: scale(12),
    padding: scale(12),
  },
  bioLabel: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.grey[600],
    textTransform: 'uppercase',
    letterSpacing: scale(0.5),
    marginBottom: verticalScale(4),
  },
  bioText: {
    fontSize: fontSize[13],
    fontFamily: fonts.Regular,
    color: colors.black[500],
    lineHeight: verticalScale(18),
  },
  sectionContainer: {
    marginBottom: verticalScale(16),
  },
  sectionTitle: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.grey[600],
    textTransform: 'uppercase',
    letterSpacing: scale(0.5),
    marginBottom: verticalScale(8),
    paddingHorizontal: scale(4),
  },
  actionCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    overflow: 'hidden',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(16),
    backgroundColor: colors.white[100],
  },
  actionRowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
  },
  actionIconBg: {
    width: scale(36),
    height: verticalScale(36),
    borderRadius: scale(12),
    backgroundColor: colors.grey[100] ?? '#F8F9FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: {
    fontSize: fontSize[16],
    fontFamily: fonts.Medium,
    color: colors.black[500],
  },
  dangerSection: {
    marginTop: verticalScale(8),
    gap: scale(12),
  },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: verticalScale(48),
    borderRadius: scale(12),
    backgroundColor: colors.white[100],
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    gap: scale(8),
  },
  logoutBtnText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: '#BA1A1A', // error color
  },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: verticalScale(48),
    borderRadius: scale(12),
    gap: scale(8),
  },
  deleteBtnText: {
    fontSize: fontSize[12],
    fontFamily: fonts.SemiBold,
    color: '#BA1A1A',
    opacity: 0.8,
  },
  appInfoText: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[600],
    textAlign: 'center',
    marginTop: verticalScale(8),
    marginBottom: verticalScale(24),
  }
});