import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../../constants';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.purple[50],
	},
	header: {
		minHeight: verticalScale(56),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: scale(8),
		backgroundColor: colors.white[100],
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: colors.purple[200],
	},
	headerButton: {
		width: scale(44),
		height: verticalScale(44),
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerSpacer: {
		width: scale(44),
	},
	headerTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
	},
	content: {
		padding: scale(16),
		paddingBottom: scale(150),
		gap: scale(16),
	},
	stepRow: {
		paddingVertical: scale(4),
	},
	step: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.purple[700],
		textTransform: 'uppercase',
		letterSpacing: 0.8,
	},
	heading: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[18],
		color: colors.black[250],
		marginTop: scale(3),
	},
	serviceSummary: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(10),
		padding: scale(12),
		borderRadius: scale(14),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(4),
		elevation: 1,
	},
	serviceImage: {
		width: scale(64),
		height: scale(64),
		borderRadius: scale(10),
	},
	serviceImagePlaceholder: {
		width: scale(64),
		height: scale(64),
		borderRadius: scale(10),
		backgroundColor: colors.purple[100],
		alignItems: 'center',
		justifyContent: 'center',
	},
	serviceCopy: {
		flex: 1,
	},
	serviceTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
	},
	serviceProvider: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
		marginTop: scale(3),
	},
	servicePrice: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[16],
		color: colors.purple[700],
		marginTop: scale(5),
	},
	section: {
		gap: scale(9),
		padding: scale(14),
		borderRadius: scale(14),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.04,
		shadowRadius: scale(3),
		elevation: 1,
	},
	label: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
	},
	datePicker: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(10),
		padding: scale(10),
		borderRadius: scale(12),
		backgroundColor: colors.purple[50],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
	},
	selectionIcon: {
		width: scale(44),
		height: scale(44),
		borderRadius: scale(11),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
	},
	selectionCopy: {
		flex: 1,
	},
	helper: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	selectionValue: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
		marginTop: scale(3),
	},
	hint: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	dateList: {
		gap: scale(8),
		paddingTop: scale(3),
	},
	dateChip: {
		width: scale(64),
		paddingVertical: scale(9),
		borderRadius: scale(11),
		alignItems: 'center',
		backgroundColor: colors.white[100],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
	},
	dateChipActive: {
		backgroundColor: colors.purple[700],
		borderColor: colors.purple[700],
	},
	dateDay: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	dateNumber: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
		marginTop: scale(3),
	},
	dateTextActive: {
		color: colors.white[100],
	},
	timeGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: scale(8),
	},
	timeChip: {
		width: '48%',
		paddingVertical: scale(11),
		borderRadius: scale(11),
		alignItems: 'center',
		backgroundColor: colors.white[100],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
	},
	timeChipActive: {
		backgroundColor: colors.purple[700],
		borderColor: colors.purple[700],
	},
	timeText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
	},
	sectionTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(7),
	},
	sectionTitle: {
		flex: 1,
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[15],
		color: colors.black[250],
	},
	instructionsInput: {
		minHeight: verticalScale(78),
		padding: scale(11),
		borderRadius: scale(10),
		backgroundColor: colors.purple[50],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
		fontFamily: fonts.Regular,
		fontSize: fontSize[13],
		color: colors.black[250],
	},
	changeButton: {
		marginLeft: 'auto',
	},
	changeText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[12],
		color: colors.purple[700],
	},
	addressCard: {
		padding: scale(11),
		borderRadius: scale(10),
		backgroundColor: colors.purple[50],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
		gap: scale(4),
	},
	addressTop: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(6),
	},
	homeBadge: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[10],
		color: colors.purple[700],
		backgroundColor: colors.purple[200],
		paddingHorizontal: scale(7),
		paddingVertical: scale(3),
		borderRadius: scale(10),
	},
	addressValue: {
		padding: scale(0),
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
		marginTop: scale(4),
	},
	unitLabel: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	unitInput: {
		height: verticalScale(40),
		paddingHorizontal: scale(10),
		borderRadius: scale(9),
		backgroundColor: colors.purple[50],
		borderWidth: scale(1),
		borderColor: colors.purple[200],
		fontFamily: fonts.Regular,
		fontSize: fontSize[12],
		color: colors.black[250],
	},
	bottomBar: {
		position: 'absolute',
		left: scale(0),
		right: scale(0),
		bottom: verticalScale(0),
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(12),
		paddingHorizontal: scale(16),
		paddingTop: scale(11),
		paddingBottom: scale(24),
		backgroundColor: 'rgba(255,255,255,0.96)',
		shadowColor: colors.black[400],
		shadowOffset: { width: scale(0), height: -3 },
		shadowOpacity: 0.08,
		shadowRadius: scale(10),
		elevation: 8,
	},
	totalCopy: {
		flex: 1,
		minWidth: 0,
	},
	slotSummary: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
	},
	slotText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.black[250],
	},
	total: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[20],
		color: colors.black[250],
		marginTop: scale(3),
	},
	totalLabel: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	continueButton: {
		flex: 1,
		minHeight: verticalScale(48),
		borderRadius: scale(11),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(6),
		backgroundColor: colors.purple[700],
	},
	continueText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.white[100],
	},
	bookingOverlay: {
		...StyleSheet.absoluteFill,
		zIndex: 10,
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(12),
		backgroundColor: 'rgba(25, 16, 55, 0.78)',
	},
	bookingOverlayText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[15],
		color: colors.white[100],
	},
});
