import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale } from '../../../../constants';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.purple[50],
	},
	content: {
		padding: scale(16),
		paddingBottom: scale(32),
	},
	segmentedControl: {
		flexDirection: 'row',
		padding: scale(4),
		borderRadius: scale(12),
		backgroundColor: colors.purple[200],
		marginBottom: scale(16),
	},
	segment: {
		flex: 1,
		minHeight: scale(42),
		borderRadius: scale(9),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(6),
	},
	segmentActive: {
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.08,
		shadowRadius: scale(3),
		elevation: 2,
	},
	segmentText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[12],
		color: colors.grey[700],
	},
	segmentTextActive: {
		color: colors.purple[700],
	},
	sectionGap: {
		gap: scale(20),
	},
	summaryGrid: {
		flexDirection: 'row',
		gap: scale(12),
	},
	summaryCard: {
		flex: 1,
		minHeight: scale(150),
		padding: scale(14),
		borderRadius: scale(16),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.06,
		shadowRadius: scale(4),
		elevation: 2,
	},
	summaryIcon: {
		width: scale(36),
		height: scale(36),
		borderRadius: scale(11),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[100],
		marginBottom: scale(12),
	},
	summaryLabel: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.grey[700],
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	summaryValue: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[20],
		color: colors.black[250],
		marginTop: scale(3),
	},
	summaryDetail: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[600],
		marginTop: scale(3),
	},
	section: {
		gap: scale(10),
	},
	sectionHeadingRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: scale(2),
	},
	sectionTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
	},
	sectionMeta: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[600],
	},
	earningItem: {
		flexDirection: 'row',
		alignItems: 'center',
		padding: scale(14),
		borderRadius: scale(16),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(3),
		elevation: 1,
	},
	itemIcon: {
		width: scale(44),
		height: scale(44),
		borderRadius: scale(12),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[100],
		marginRight: scale(10),
	},
	itemCopy: {
		flex: 1,
		minWidth: 0,
	},
	itemTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
	},
	itemMetaRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginTop: scale(4),
		gap: scale(6),
	},
	itemMeta: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[600],
	},
	dot: {
		width: scale(4),
		height: scale(4),
		borderRadius: scale(2),
		backgroundColor: colors.grey[400],
	},
	completed: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.purple[700],
		backgroundColor: colors.purple[100],
		paddingHorizontal: scale(7),
		paddingVertical: scale(3),
		borderRadius: scale(8),
	},
	amountCopy: {
		alignItems: 'flex-end',
		marginLeft: scale(8),
	},
	amount: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
	},
	ratingCard: {
		alignItems: 'center',
		padding: scale(20),
		borderRadius: scale(16),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.06,
		shadowRadius: scale(4),
		elevation: 2,
	},
	ratingIcon: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
		marginBottom: scale(8),
	},
	ratingValueRow: {
		flexDirection: 'row',
		alignItems: 'baseline',
	},
	ratingValue: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[30],
		color: colors.black[250],
	},
	ratingOutOf: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[14],
		color: colors.grey[700],
		marginLeft: scale(3),
	},
	stars: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(2),
		marginVertical: scale(6),
	},
	ratingDescription: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[12],
		color: colors.grey[700],
	},
	trustRow: {
		flexDirection: 'row',
		width: '100%',
		marginTop: scale(16),
		padding: scale(12),
		borderRadius: scale(12),
		backgroundColor: colors.purple[100],
	},
	trustMetric: {
		flex: 1,
		alignItems: 'center',
	},
	trustValue: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
	},
	reviewCard: {
		padding: scale(14),
		borderRadius: scale(16),
		backgroundColor: colors.white[100],
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(3),
		elevation: 1,
	},
	reviewHeader: {
		flexDirection: 'row',
		alignItems: 'flex-start',
	},
	reviewerAvatar: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(20),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
		marginRight: scale(10),
	},
	reviewerInitial: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.purple[700],
	},
	reviewerCopy: {
		flex: 1,
	},
	reviewerName: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
	},
	reviewRating: {
		alignItems: 'flex-end',
	},
	reviewText: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[13],
		lineHeight: scale(20),
		color: colors.black[250],
		backgroundColor: colors.purple[100],
		padding: scale(10),
		borderRadius: scale(10),
		marginTop: scale(12),
	},
	reviewFooter: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginTop: scale(10),
	},
	verifiedBooking: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
	},
	verifiedLabel: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.purple[700],
	},
});
