import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../../constants';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.purple[50],
	},
	header: {
		minHeight: verticalScale(56),
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.white[100],
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: colors.purple[200],
		paddingHorizontal: scale(8),
		gap: scale(8),
	},
	backButton: {
		width: scale(44),
		height: verticalScale(44),
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerTitle: {
		flex: 1,
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
		textAlign: 'center',
	},
	content: {
		padding: scale(16),
		paddingBottom: scale(180),
		gap: scale(12),
	},
	confirmationCard: {
		padding: scale(16),
		borderRadius: scale(14),
		backgroundColor: colors.white[100],
		gap: scale(8),
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(4),
		elevation: 1,
	},
	confirmationIcon: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(14),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
	},
	confirmationTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[18],
		color: colors.black[250],
	},
	confirmationText: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[13],
		color: colors.grey[700],
	},
	scheduleBox: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(8),
		padding: scale(10),
		borderRadius: scale(10),
		backgroundColor: colors.purple[100],
		marginTop: scale(4),
	},
	scheduleText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
	},
	headerStatus: {
		width: scale(28),
		height: scale(22),
		borderRadius: scale(12),
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerStatusDot: {
		width: scale(8),
		height: scale(8),
		borderRadius: scale(4),
	},
	card: {
		padding: scale(16),
		borderRadius: scale(14),
		backgroundColor: colors.white[100],
		gap: scale(14),
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(4),
		elevation: 1,
	},
	clientHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(12),
	},
	avatar: {
		width: scale(56),
		height: scale(56),
		borderRadius: scale(28),
		backgroundColor: colors.purple[200],
		alignItems: 'center',
		justifyContent: 'center',
	},
	avatarImage: {
		width: '100%',
		height: '100%',
		borderRadius: scale(28),
		backgroundColor: colors.purple[300],
	},
	avatarInitial: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[22],
		color: colors.purple[700],
	},
	clientCopy: {
		flex: 1,
	},
	clientName: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[17],
		color: colors.black[250],
	},
	clientLabel: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[12],
		color: colors.grey[700],
		marginTop: scale(3),
	},
	callButton: {
		height: verticalScale(44),
		borderRadius: scale(11),
		backgroundColor: colors.purple[100],
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(8),
	},
	callButtonText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.purple[700],
	},
	cardLabelRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	cardLabel: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.grey[700],
		textTransform: 'uppercase',
		letterSpacing: 0.5,
	},
	rateBadge: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[10],
		color: colors.grey[700],
		backgroundColor: colors.purple[100],
		paddingHorizontal: scale(8),
		paddingVertical: scale(4),
		borderRadius: scale(5),
	},
	serviceRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: scale(10),
	},
	serviceIcon: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(9),
		backgroundColor: colors.purple[200],
		alignItems: 'center',
		justifyContent: 'center',
	},
	serviceCopy: {
		flex: 1,
		minWidth: 0,
	},
	serviceTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[15],
		color: colors.black[250],
	},
	serviceMeta: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
		marginTop: scale(6),
		flexWrap: 'wrap',
	},
	mutedText: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	dot: {
		width: scale(4),
		height: scale(4),
		borderRadius: scale(2),
		backgroundColor: colors.grey[400],
		marginHorizontal: scale(2),
	},
	payout: {
		alignItems: 'flex-end',
	},
	payoutAmount: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[17],
		color: colors.black[250],
	},
	payoutLabel: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.purple[700],
		marginTop: scale(4),
	},
	infoRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: scale(10),
		flex: 1,
	},
	infoIcon: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(9),
		backgroundColor: colors.purple[200],
		alignItems: 'center',
		justifyContent: 'center',
	},
	infoCopy: {
		flex: 1,
		minWidth: scale(0),
		gap: scale(3),
	},
	infoValue: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.black[250],
	},
	cardDivider: {
		height: StyleSheet.hairlineWidth,
		backgroundColor: colors.purple[200],
	},
	locationRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: scale(8),
	},
	mapsButton: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(3),
		paddingHorizontal: scale(8),
		paddingVertical: scale(7),
		borderRadius: scale(7),
		backgroundColor: colors.purple[100],
	},
	mapsButtonText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.purple[700],
	},
	notesBox: {
		backgroundColor: colors.purple[100],
		borderRadius: scale(10),
		padding: scale(10),
		gap: scale(7),
	},
	notesHeading: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(6),
	},
	notesText: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[13],
		lineHeight: verticalScale(20),
		color: colors.black[250],
	},
	bottomBar: {
		position: 'absolute',
		left: scale(0),
		right: scale(0),
		bottom: verticalScale(0),
		paddingHorizontal: scale(16),
		paddingTop: scale(12),
		paddingBottom: scale(24),
		backgroundColor: 'rgba(255,255,255,0.96)',
		gap: scale(10),
		shadowColor: colors.black[400],
		shadowOffset: { width: scale(0), height: -3 },
		shadowOpacity: 0.08,
		shadowRadius: scale(10),
		elevation: 8,
	},
	acceptButton: {
		height: verticalScale(48),
		borderRadius: scale(11),
		backgroundColor: colors.purple[600],
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(8),
	},
	acceptText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.white[100],
	},
	declineButton: {
		height: verticalScale(44),
		borderRadius: scale(11),
		backgroundColor: '#FDEBEC',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(8),
	},
	declineText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.red[200],
	},
	phaseBar: {
		flexDirection: 'row',
		gap: scale(6),
		marginTop: scale(4),
	},
	phaseSegment: {
		flex: 1,
		height: scale(8),
		borderRadius: scale(4),
		backgroundColor: colors.purple[200],
	},
	phaseActive: {
		backgroundColor: colors.purple[600],
	},
	phaseLabels: {
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	phaseActiveText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.purple[700],
	},
	backBookingsButton: {
		height: verticalScale(46),
		borderRadius: scale(11),
		backgroundColor: colors.purple[100],
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(8),
	},
	backBookingsText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.purple[700],
	},
	cancelBookingButton: {
		paddingVertical: scale(8),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(6),
	},
});
