const strings = {
	verification: {
		headerTitle: 'Email Verification',
		heading: 'Verify Your Email',
		// instructions: "We've sent a 6-digit verification code to",
		instructions: "We've sent a email verification link to",
		email: 'alex.smith@example.com',

		resendPrompt: "Didn't receive code?",
		resend: 'Resend Code',
		openMailHint: 'Please open your email and verify verification to get into the app',
		verify: 'Verify & Continue',
		encrypted: 'End-to-end 256-bit encrypted verification',
		dispatched: 'New code dispatched via Email',
		verified: 'Verified',
		invalidCode: 'Enter the full 6-digit code',
		updateEmail: 'Update Email Address',
		cancel: 'Cancel',
		save: 'Save',
	},
	common: {
		brand: 'ProServe',
		back: 'Go back',
		edit: 'Edit',
		phone: 'Phone',
		email: 'Email',
		logOut: 'Log Out',
		logOutTitle: 'Log Out?',
		logOutMessage: 'Are you sure you want to log out?',
		deleteAccount: 'Delete Account',
		deleteAccountTitle: 'Delete Account?',
		keepAccount: 'Keep Account',
		cancel: 'Cancel',
		helpSupport: 'Help & Support',
		terms: 'Terms',
		termsAndConditions: 'Terms & Conditions',
		privacyPolicy: 'Privacy Policy',
		signIn: 'Sign In',
		alreadyHaveAccount: 'Already have an account?',
		continue: 'Continue',
	},
	welcome: {
		heading: 'Welcome to ProServe',
		subheading: 'Every home service, handled by trusted pros.',
		customerTitle: 'I need a service',
		customerDescription: 'Book top-rated cleaners, plumbers, technicians & handymen in minutes.',
		providerTitle: 'I provide services',
		providerDescription: 'Manage bookings, expand your client base, and get paid securely.',
		providerBadge: 'Earn & Grow',
	},
	signUp: {
		providerRegistration: 'Provider Registration',
		customerRegistration: 'Customer Registration',
		providerHeading: 'Join as a Service Provider',
		customerHeading: 'Create Account',
		providerSubheading: 'Start receiving verified customer job requests and grow your business.',
		customerSubheading: 'Join ProServe as a Customer and book trusted professionals.',
		fullLegalName: 'Full Legal Name',
		fullName: 'Full Name',
		serviceName: 'Service Name',
		experience: 'Years of Experience',
		businessEmail: 'Business Email Address',
		mobilePhone: 'Mobile Phone Number',
		email: 'Email Address',
		phone: 'Phone Number',
		password: 'Password',
		providerTerms: 'Provider Terms',
		terms: 'Terms of Service',
		backgroundCheck: 'Background Check Policy',
		privacy: 'Privacy Policy',
		termsAgreement: "By continuing, I agree to ProServe's",
		agreementJoiner: 'and',
		providerSubmit: 'Continue to Verification',
		customerSubmit: 'Create Account',
	},
	login: {
		customerTitle: 'Customer Sign In',
		providerTitle: 'Provider Sign In',
		heading: 'Welcome back',
		customerSubheading: 'Log in to manage your appointments, schedules, and active services.',
		providerSubheading: 'Log in to manage your bookings, schedule, and active services.',
		customerRole: 'Customer',
		providerRole: 'Service Provider',
		email: 'Email Address',
		emailPlaceholder: 'name@example.com',
		password: 'Password',
		passwordPlaceholder: 'Enter your secure password',
		rememberMe: 'Remember me',
		forgotPassword: 'Forgot password?',
		submit: 'Sign In',
		noAccount: "Don't have an account?",
		signUp: 'Sign Up',
	},
	resetPassword: {
		customerTitle: 'Customer Reset Password',
		providerTitle: 'Provider Reset Password',
		heading: 'Reset Your Password',
		subheading: 'Enter your registered email address to receive password recovery instructions.',
		emailLabel: 'Registered Email Address',
		emailPlaceholder: 'name@example.com',
		submitEmail: 'Send Reset Link',
		successTitle: 'Reset email sent',
		successMessage: 'We sent a password reset link to',
		successNextStep: 'Open the email, choose a new password, then return here to sign in.',
		successButton: 'Go to Sign In',
		rememberPasswordPrompt: 'Remember your password?',
		signIn: 'Sign In',
	},
	auth: {
		profileLoadError: 'Unable to load your profile. Please sign in again.',
		signOut: 'Sign Out',
	},
	home: {
		subtitle: 'Home',
		greeting: 'Hello, John',
		greetingSub: "Ready for today's jobs?",
		availableNow: 'Available Now',
		todaysOverview: "Today's Overview",
		quickActions: 'Quick Actions',
		recentBookings: 'Recent Bookings',
		latest: '3 latest',
		viewAll: 'View All',
		review: 'Review',
	},
	updatePassword: {
		title: 'Create New Password',
		heading: 'Create New Password',
		subheading: 'Your new password must be different from previous passwords and contain strong security credentials.',
		currentPasswordLabel: 'Current Password',
		currentPasswordPlaceholder: 'Enter current or temporary code',
		currentPasswordRequired: 'Required',
		newPasswordLabel: 'New Password',
		newPasswordPlaceholder: 'Enter new secure password',
		confirmPasswordLabel: 'Confirm New Password',
		confirmPasswordPlaceholder: 'Re-enter new password',
		matched: 'Matched',
		strengthHeader: 'Password Requirements',
		reqLength: 'At least 8 characters long',
		reqNumber: 'At least one number (0-9)',
		reqSymbol: 'At least one special symbol (!@#$%^&*)',
		tooShort: 'Too Short',
		weak: 'Weak',
		moderate: 'Moderate',
		strong: 'Strong & Secure',
		submit: 'Update Password & Sign In',
		updating: 'Securing Workspace...',
		updated: 'Credentials Updated!',
		cancel: 'Cancel & Return to Sign In',
		securityTip: 'Tip: Never share your account password with anyone to keep your account safe.',
	},
	providerBookings: {
		headerTitle: 'My Bookings',
		searchPlaceholder: 'Search client name or service...',
		tabAll: 'All',
		tabPending: 'Pending',
		tabUpcoming: 'Upcoming',
		tabCompleted: 'Completed',
		tabCancelled: 'Cancelled',
		tabExpired: 'Expired',
		accept: 'Accept',
		decline: 'Decline',
		call: 'Call',
		details: 'Details',
		directions: 'Directions',
		complete: 'Complete Job',
		viewReceipt: 'View Receipt',
		noBookingsTitle: 'No Bookings Found',
		noBookingsSub: 'You have no bookings under this category right now.',
	},
	alerts: {
		accountNotFound: 'Account not found',
		notRegistered: 'You are not registered with the app. Please create an account first.',
		invalidEmail: 'Invalid email',
		validEmail: 'Please enter a valid email address.',
		unableToSendEmail: 'Unable to send email',
		resetEmailFailed: 'We could not send the password reset email. Please try again.',
		sessionExpired: 'Session expired',
		pleaseSignInAgain: 'Please sign in again before continuing.',
		missingInformation: 'Missing information',
		unableToSave: 'Unable to save',
		tryAgain: 'Please try again.',
	},
	commonForms: {
		cancel: 'Cancel',
		createService: 'Create Service',
		saveChanges: 'Save Changes',
		saving: 'Saving...',
		loading: 'Loading...',
		fullName: 'Full Name',
		phoneNumber: 'Phone Number',
		emailAddress: 'Email Address',
		yourFullName: 'Your full name',
		yourPhoneNumber: 'Your phone number',
		yourEmailAddress: 'Your email address',
		emailManaged: 'Email is managed through your account.',
	},
	profile: {
		profile: 'Profile',
		profileEditor: 'Profile Editor',
		editProfile: 'Edit Profile',
		providerAccount: 'Provider account',
		personalInformation: 'Personal Information',
		businessInformation: 'Business Information',
		businessName: 'Business Name',
		businessCategory: 'Business Category',
		yearsExperience: 'Years of Experience',
		providerBusinessPlaceholder: 'Your service business',
		categoryPlaceholder: 'e.g. Home repair',
		experiencePlaceholder: 'e.g. 8 years',
		providerAvailabilityDescription: "You won't receive new on-demand booking requests for the rest of today once switched offline."
	},
	providerProfile: {
		verifiedProvider: 'Verified Provider',
		providerFallbackName: 'Provider',
		businessFallbackName: 'Your Business',
		onlineActive: 'Online & Active',
		offline: 'Offline',
		todaysAvailability: "Today's Availability",
		availabilitySub: 'Live dispatch & instant booking status',
		onlineAvailable: 'Online & Available',
		offlineToday: 'Offline Today',
		goOfflineToday: 'Go Offline Today',
		resumeAvailability: 'Resume Availability',
		performanceInsights: 'Performance & Insights',
		viewEarningsReviews: 'View Earnings & Reviews →',
		earnings: 'Earnings',
		rating: 'Rating',
		reviewsCount: '(128 reviews)',
		profileInformation: 'Profile Information',
		manageBusiness: 'Manage Business',
		earningsReviews: 'Earnings & Reviews',
		settingsSupport: 'Settings & Support',
		deleteAccountMessage: 'This will remove your profile, active bookings, and payout history.',
		deleteConfirm: 'Yes, Delete',
	},
	customerProfile: {
		customerFallbackName: 'Customer',
		preferencesSettings: 'Preferences & Settings',
		savedAddresses: 'Saved Addresses',
		savedAddress: 'Home: 128 Pinecrest Blvd',
		placesCount: '2 Places',
		informationSupport: 'Information & Support',
		deleteAccountMessage: 'All your booking history and reviews will be permanently removed.',
	},
	servicesForm: {
		newService: 'New Service',
		editService: 'Edit Service',
		basicInformation: 'Basic Information',
		pricingTiming: 'Pricing & Timing',
		description: 'Service Description',
		status: 'Service Status',
		coverPhoto: 'Service Cover Photo',
		startingPrice: 'Starting Price',
		clientScope: 'Client-Facing Scope',
		baseBilling: 'Base tier billing',
		slotAllocation: 'Slot allocation',
		activeMarketplace: 'Active in marketplace',
		hiddenMarketplace: 'Hidden from marketplace',
		activeDescription: 'Clients can discover and request this service.',
		hiddenDescription: 'Clients will not see this service.',
		deleteService: 'Delete Service',
		deleteConfirmTitle: 'Delete this service?',
	},
	customerBookings: {
		upcoming: 'Upcoming',
		completed: 'Completed',
		cancelled: 'Cancelled',
		expired: 'Expired',
		viewDetails: 'View Details',
		rateBooking: 'Rate Booking',
		noUpcoming: 'No bookings found',
		upcomingEmpty: 'Your upcoming bookings will appear here.',
		noCompleted: 'No bookings found',
		completedEmpty: 'Completed bookings will appear here after a service is finished.',
		noCancelled: 'No cancelled bookings',
		cancelledEmpty: 'Cancelled bookings will appear here.',
		noExpired: 'No expired bookings',
		expiredEmpty: 'Bookings that were not accepted before their scheduled time will appear here.',
	},
	services: {
		addService: 'Add Service',
		edit: 'Edit',
		noServices: 'No services found',
		providerEmpty: 'Add your first service to start receiving booking requests.',
		customerEmpty: 'Providers have not published services yet.',
		loading: 'Loading services...',
		serviceNamePlaceholder: 'e.g. Deluxe Carpet Steam Cleaning',
		pricePlaceholder: '0.00',
		descriptionPlaceholder: 'Describe the specifics of what is covered...',
	},
	booking: {
		bookService: 'Book Service',
		pickDateTime: 'Pick Date & Time',
		serviceDate: 'Service Date',
		arrivalWindow: 'Arrival Window / Time',
		specialInstructions: 'Special Instructions',
		instructionsHint: 'Any delicate surfaces, focus areas, or pet instructions?',
		instructionsPlaceholder: 'Add notes for your service provider...',
		serviceAddress: 'Service Address',
		change: 'Change',
		bookTheService: 'Book the service',
		noHiddenFees: 'No hidden fees',
		cancelBooking: 'Cancel Booking',
	},
	notifications: {
		title: 'Notifications',
		noNotifications: 'No Notifications',
		caughtUp: "You're all caught up!",
		caughtUpMessage: 'Booking alerts & status changes appear here in real-time.',
	},
} as const;

export default strings;
