import { StyleSheet } from 'react-native';
import { colors, fonts, scale, verticalScale } from '../../../../constants';
import { fontSize } from '../../../../constants/metrics';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white[100] ?? '#FAFAFA',
  },
  contentContainer: {
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(80),
  },
  header: {
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(250, 248, 255, 0.8)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
  },
  logo: {
    width: scale(32),
    height: verticalScale(32),
    resizeMode: 'contain',
  },
  headerTitleContainer: {
    flexDirection: 'column',
  },
  headerTitle: {
    fontSize: fontSize[14],
    fontFamily: fonts.Bold,
    color: colors.black[500],
    lineHeight: verticalScale(20),
  },
  headerSubtitle: {
    fontSize: fontSize[12],
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    lineHeight: verticalScale(16),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  notificationBtn: {
    width: scale(44),
    height: verticalScale(44),
    borderRadius: scale(22),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: verticalScale(8),
    right: scale(8),
    width: scale(8),
    height: verticalScale(8),
    borderRadius: scale(4),
    backgroundColor: colors.purple[700],
    borderWidth: scale(2),
    borderColor: colors.white[100],
  },
  heroCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(20),
    marginBottom: verticalScale(20),
    marginTop: verticalScale(8),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    overflow: 'hidden',
  },
  heroBlur: {
    position: 'absolute',
    right: scale(-32),
    top: verticalScale(-32),
    width: scale(144),
    height: verticalScale(144),
    borderRadius: scale(72),
    backgroundColor: 'rgba(226, 223, 255, 0.4)',
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: scale(16),
    zIndex: 10,
  },
  avatarContainer: {
    position: 'relative',
  },
  avatar: {
    width: scale(80),
    height: verticalScale(80),
    borderRadius: scale(40),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: verticalScale(0),
    right: scale(0),
    width: scale(20),
    height: verticalScale(20),
    borderRadius: scale(10),
    backgroundColor: colors.purple[700],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: scale(2),
    borderColor: colors.white[100],
  },
  heroInfo: {
    flex: 1,
  },
  heroNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(4),
  },
  heroName: {
    flex: 1,
    fontSize: fontSize[20],
    fontFamily: fonts.Bold,
    color: colors.black[500],
  },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(4),
    borderRadius: scale(12),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
  },
  editBtnText: {
    fontSize: fontSize[12],
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    marginTop: verticalScale(4),
  },
  contactText: {
    fontSize: fontSize[13],
    fontFamily: fonts.Regular,
    color: colors.grey[700],
  },
  sectionContainer: {
    marginBottom: verticalScale(20),
  },
  sectionTitle: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
    marginBottom: verticalScale(8),
    paddingHorizontal: scale(4),
  },
  cardBlock: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: scale(16),
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
    flex: 1,
  },
  menuIconContainer: {
    width: scale(40),
    height: verticalScale(40),
    borderRadius: scale(20),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIconContainerSecondary: {
    backgroundColor: colors.purple[700],
  },
  menuItemTexts: {
    flex: 1,
  },
  menuTitle: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
    marginBottom: verticalScale(2),
  },
  menuSubtitle: {
    fontSize: fontSize[13],
    fontFamily: fonts.Regular,
    color: colors.grey[700],
  },
  menuItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  menuStatusBadge: {
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: scale(10),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
  },
  menuStatusText: {
    fontSize: fontSize[11],
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
  },
  divider: {
    height: verticalScale(1),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
  },
  actionsContainer: {
    gap: scale(12),
  },
  logoutBtn: {
    height: verticalScale(48),
    borderRadius: scale(16),
    backgroundColor: colors.white[100],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scale(8),
    shadowColor: colors.grey[400],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: scale(3),
    elevation: 2,
  },
  logoutText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
  },
  deleteBtn: {
    paddingVertical: verticalScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scale(6),
  },
  deleteText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: '#E11D48',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(40, 48, 68, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(16),
  },
  modalContent: {
    width: '100%',
    backgroundColor: colors.white[100],
    borderRadius: scale(24),
    padding: scale(24),
    alignItems: 'center',
  },
  modalIconContainer: {
    width: scale(48),
    height: verticalScale(48),
    borderRadius: scale(24),
    backgroundColor: '#FFE4E6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(16),
  },
  modalTitle: {
    fontSize: fontSize[18],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
    marginBottom: verticalScale(8),
  },
  modalDesc: {
    fontSize: fontSize[14],
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    textAlign: 'center',
    marginBottom: verticalScale(24),
  },
  modalBtnPrimary: {
    width: '100%',
    height: verticalScale(48),
    borderRadius: scale(16),
    backgroundColor: '#E11D48',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(12),
  },
  modalBtnPrimaryText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.white[100],
  },
  modalBtnSecondary: {
    width: '100%',
    height: verticalScale(48),
    borderRadius: scale(16),
    backgroundColor: colors.grey[100] ?? '#F2F3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnSecondaryText: {
    fontSize: fontSize[14],
    fontFamily: fonts.SemiBold,
    color: colors.black[500],
  }
});