import { Platform, StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.purple[50],
  },
  headerContainer: {
    ...Platform.select({
      ios: {
        shadowColor: colors.black[400],
        shadowOffset: { width: scale(0), height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: scale(8),
      },
      android: {
        elevation: 2,
      },
    }),
  },
  headerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    minWidth: scale(0),
  },
  headerLogo: {
    width: scale(32),
    height: scale(32),
  },
  headerTitles: {
    minWidth: scale(0),
  },
  headerTitle: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[16],
    fontWeight: '600',
    lineHeight: verticalScale(22),
  },
  headerSubtitle: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[12],
    lineHeight: verticalScale(16),
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  headerIconButton: {
    width: scale(44),
    height: scale(44),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(22),
  },
  notificationDot: {
    position: 'absolute',
    top: scale(10),
    right: scale(10),
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    backgroundColor: colors.red[200],
    borderWidth: scale(2),
    borderColor: colors.white[100],
  },
  profileButton: {
    width: scale(44),
    height: scale(44),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: scale(22),
    backgroundColor: colors.purple[200],
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(8),
    paddingBottom: verticalScale(24),
  },
  greetingSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(12),
  },
  greetingTextWrap: {
    flex: 1,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  greetingTitle: {
    fontFamily: fonts.Bold,
    color: colors.black[250],
    fontSize: fontSize[22],
    fontWeight: '700',
    lineHeight: verticalScale(28),
  },
  greetingEmoji: {
    fontSize: fontSize[20],
    lineHeight: verticalScale(24),
  },
  greetingSubtext: {
    marginTop: verticalScale(2),
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
  },
  availabilityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    paddingHorizontal: scale(10),
    paddingVertical: verticalScale(4),
    borderRadius: scale(999),
    backgroundColor: colors.purple[200],
  },
  availabilityDot: {
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    backgroundColor: colors.green[350],
  },
  availabilityText: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontSize: fontSize[11],
    fontWeight: '600',
    lineHeight: verticalScale(14),
  },
  section: {
    marginTop: verticalScale(12),
  },
  sectionLg: {
    marginTop: verticalScale(20),
  },
  sectionTitle: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[14],
    fontWeight: '600',
    lineHeight: verticalScale(20),
    marginBottom: verticalScale(10),
  },
  sectionTitleInline: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[14],
    fontWeight: '600',
    lineHeight: verticalScale(20),
  },
  overviewGrid: {
    flexDirection: 'row',
    gap: scale(10),
  },
  overviewCard: {
    flex: 1,
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(12),
    ...Platform.select({
      ios: {
        shadowColor: colors.black[400],
        shadowOffset: { width: scale(0), height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: scale(4),
      },
      android: {
        elevation: 1,
      },
    }),
  },
  overviewCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  overviewIconWrap: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(12),
    alignItems: 'center',
    justifyContent: 'center',
  },
  overviewBadge: {
    paddingHorizontal: scale(6),
    paddingVertical: verticalScale(2),
    borderRadius: scale(999),
  },
  overviewBadgeText: {
    fontFamily: fonts.SemiBold,
    fontSize: fontSize[11],
    fontWeight: '600',
    lineHeight: verticalScale(14),
  },
  overviewCardBottom: {
    marginTop: verticalScale(12),
  },
  overviewCount: {
    fontFamily: fonts.Bold,
    fontSize: fontSize[26],
    fontWeight: '700',
    lineHeight: verticalScale(30),
  },
  overviewTitle: {
    marginTop: verticalScale(4),
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
    fontSize: fontSize[11],
    fontWeight: '600',
    lineHeight: verticalScale(14),
  },
  quickActionsGrid: {
    flexDirection: 'row',
    gap: scale(10),
  },
  quickActionCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(12),
    ...Platform.select({
      ios: {
        shadowColor: colors.black[400],
        shadowOffset: { width: scale(0), height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: scale(4),
      },
      android: {
        elevation: 1,
      },
    }),
  },
  quickActionIconWrap: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(12),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: verticalScale(8),
  },
  quickActionLabel: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[12],
    fontWeight: '600',
    lineHeight: verticalScale(16),
    textAlign: 'center',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: verticalScale(12),
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    flex: 1,
  },
  countBadge: {
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: scale(999),
    backgroundColor: colors.purple[200],
  },
  countBadgeText: {
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
    fontSize: fontSize[12],
    fontWeight: '600',
    lineHeight: verticalScale(16),
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(2),
  },
  viewAllText: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontSize: fontSize[12],
    fontWeight: '600',
    lineHeight: verticalScale(16),
  },
  bookingList: {
    gap: verticalScale(10),
  },
  bookingCard: {
    backgroundColor: colors.white[100],
    borderRadius: scale(16),
    padding: scale(14),
    gap: verticalScale(10),
    ...Platform.select({
      ios: {
        shadowColor: colors.black[400],
        shadowOffset: { width: scale(0), height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: scale(4),
      },
      android: {
        elevation: 1,
      },
    }),
  },
  bookingCardCompleted: {
    opacity: 0.9,
  },
  bookingCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: scale(8),
  },
  bookingClient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
    minWidth: scale(0),
  },
  bookingAvatar: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: colors.purple[400],
  },
  bookingClientInfo: {
    flex: 1,
    minWidth: scale(0),
  },
  bookingClientName: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[16],
    fontWeight: '600',
    lineHeight: verticalScale(22),
  },
  bookingServiceTitle: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
    height: verticalScale(24),
    paddingHorizontal: scale(10),
    borderRadius: scale(999),
  },
  statusDot: {
    width: scale(6),
    height: scale(6),
    borderRadius: scale(3),
  },
  statusBadgeText: {
    fontFamily: fonts.SemiBold,
    fontSize: fontSize[11],
    fontWeight: '600',
    lineHeight: verticalScale(14),
  },
  bookingCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: verticalScale(8),
  },
  bookingTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    flex: 1,
  },
  bookingTimeText: {
    fontFamily: fonts.Medium,
    color: colors.black[250],
    fontSize: fontSize[12],
    fontWeight: '500',
    lineHeight: verticalScale(16),
  },
  bookingTimeTextMuted: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontWeight: '400',
  },
  bookingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  bookingActionButton: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[100],
  },
  bookingActionButtonPrimary: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[300],
  },
  reviewButton: {
    height: verticalScale(32),
    paddingHorizontal: scale(12),
    borderRadius: scale(999),
    minHeight: verticalScale(32),
  },
  reviewButtonText: {
    fontFamily: fonts.SemiBold,
    fontSize: fontSize[11],
    lineHeight: verticalScale(14),
  },
  priceTag: {
    paddingHorizontal: scale(8),
    paddingVertical: verticalScale(2),
    borderRadius: scale(6),
    backgroundColor: '#ECFDF5',
  },
  priceTagText: {
    fontFamily: fonts.SemiBold,
    color: '#047857',
    fontSize: fontSize[11],
    fontWeight: '600',
    lineHeight: verticalScale(14),
  },
});
