import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, sWidth, verticalScale } from '../../../../constants';

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.purple[50],
	},
	header: {
		minHeight: verticalScale(56),
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.white[100],
		borderBottomWidth: StyleSheet.hairlineWidth,
		borderBottomColor: colors.purple[200],
		paddingHorizontal: scale(8),
		gap: scale(8),
	},
	headerButton: {
		width: scale(44),
		height: verticalScale(44),
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerTitle: {
		flex: 1,
		textAlign: 'center',
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
	},
	profileIcon: {
		width: scale(32),
		height: scale(32),
		borderRadius: scale(16),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[600],
	},
	content: {
		padding: scale(16),
		paddingBottom: scale(120),
		gap: scale(14),
	},
	contextRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	categoryBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
		backgroundColor: colors.purple[200],
		borderRadius: scale(20),
		paddingHorizontal: scale(10),
		paddingVertical: scale(6),
	},
	categoryText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.purple[700],
		textTransform: 'uppercase',
	},
	shareButton: {
		width: scale(36),
		height: scale(36),
		borderRadius: scale(18),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[100],
	},
	card: {
		padding: scale(16),
		borderRadius: scale(16),
		backgroundColor: colors.white[100],
		gap: scale(12),
		shadowColor: colors.black[400],
		shadowOpacity: 0.05,
		shadowRadius: scale(4),
		elevation: 1,
	},
	carouselWrap: {
		width: sWidth - scale(32),
		height: verticalScale(176),
		borderRadius: scale(12),
		overflow: 'hidden',
		backgroundColor: colors.purple[100],
		position: 'relative',
		alignSelf: 'center',
	},
	carouselImageContainer: {
		width: sWidth - scale(32),
		height: verticalScale(176),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[100],
		overflow: 'hidden',
	},
	carouselImage: {
		width: sWidth - scale(32),
		height: verticalScale(176),
		resizeMode: 'cover',
	},
	carouselDots: {
		flexDirection: 'row',
		alignSelf: 'center',
		gap: scale(6),
		position: 'absolute',
		bottom: scale(8),
	},
	dot: {
		width: scale(8),
		height: scale(8),
		borderRadius: scale(4),
	},
	dotActive: {
		backgroundColor: colors.purple[700],
	},
	dotInactive: {
		backgroundColor: colors.purple[300],
	},
	durationBadge: {
		position: 'absolute',
		bottom: scale(8),
		right: scale(8),
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
		backgroundColor: 'rgba(255,255,255,0.92)',
		paddingHorizontal: scale(8),
		paddingVertical: scale(5),
		borderRadius: scale(14),
	},
	badgeText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.black[250],
	},
	serviceTitle: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[22],
		color: colors.black[250],
	},
	description: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[14],
		lineHeight: verticalScale(20),
		color: colors.grey[700],
	},
	priceRow: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		justifyContent: 'space-between',
		paddingTop: scale(4),
	},
	caption: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	priceLine: {
		flexDirection: 'row',
		alignItems: 'baseline',
	},
	price: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[26],
		color: colors.purple[700],
	},
	mutedText: {
		fontFamily: fonts.Regular,
		fontSize: fontSize[11],
		color: colors.grey[700],
	},
	feeBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
		backgroundColor: colors.purple[100],
		paddingHorizontal: scale(8),
		paddingVertical: scale(6),
		borderRadius: scale(8),
	},
	providerRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(10),
	},
	providerAvatar: {
		width: scale(48),
		height: scale(48),
		borderRadius: scale(24),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
	},
	providerCopy: {
		flex: 1,
	},
	providerName: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
	},
	ratingRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(4),
		marginTop: scale(3),
	},
	ratingText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[11],
		color: colors.black[250],
	},
	eliteBadge: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[10],
		color: colors.purple[700],
		backgroundColor: colors.purple[100],
		paddingHorizontal: scale(8),
		paddingVertical: scale(5),
		borderRadius: scale(6),
	},
	availability: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: scale(10),
		padding: scale(16),
		borderRadius: scale(16),
		backgroundColor: colors.purple[100],
	},
	availabilityIcon: {
		width: scale(40),
		height: scale(40),
		borderRadius: scale(20),
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.purple[200],
	},
	availabilityTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[13],
		color: colors.black[250],
		marginBottom: scale(3),
	},
	reviewHeading: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	reviewTitle: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[16],
		color: colors.black[250],
	},
	reviewCard: {
		padding: scale(12),
		borderRadius: scale(12),
		backgroundColor: colors.purple[100],
		gap: scale(8),
	},
	bottomBar: {
		position: 'absolute',
		left: scale(0),
		right: scale(0),
		bottom: verticalScale(0),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: scale(14),
		paddingHorizontal: scale(16),
		paddingTop: scale(12),
		paddingBottom: scale(24),
		backgroundColor: 'rgba(255,255,255,0.96)',
		shadowColor: colors.black[400],
		shadowOffset: { width: scale(0), height: -3 },
		shadowOpacity: 0.08,
		shadowRadius: scale(10),
		elevation: 8,
	},
	total: {
		fontFamily: fonts.Bold,
		fontSize: fontSize[22],
		color: colors.black[250],
		marginTop: scale(2),
	},
	bookButton: {
		flex: 1,
		height: verticalScale(48),
		borderRadius: scale(12),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: scale(8),
		backgroundColor: colors.purple[700],
	},
	bookText: {
		fontFamily: fonts.SemiBold,
		fontSize: fontSize[14],
		color: colors.white[100],
	},
});
