import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.purple[50],
  },
  scrollView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: scale(16),
    paddingBottom: verticalScale(28),
  },
  intro: {
    alignItems: 'center',
    paddingTop: verticalScale(24),
    paddingBottom: verticalScale(20),
  },
  logoFrame: {
    width: scale(72),
    height: scale(72),
    borderRadius: scale(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[200],
    marginBottom: verticalScale(16),
    position: 'relative',
  },
  verifiedBadge: {
    position: 'absolute',
    bottom: -scale(4),
    right: -scale(4),
    width: scale(24),
    height: scale(24),
    borderRadius: scale(12),
    backgroundColor: colors.purple[600],
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: scale(2),
    borderColor: colors.purple[50],
  },
  heading: {
    fontFamily: fonts.Bold,
    color: colors.black[250],
    fontSize: fontSize[26],
    lineHeight: verticalScale(34),
    fontWeight: '700',
    textAlign: 'center',
  },
  subheading: {
    maxWidth: scale(310),
    marginTop: verticalScale(6),
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[14],
    lineHeight: verticalScale(20),
    textAlign: 'center',
  },
  methodSwitcher: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
    padding: scale(4),
    marginBottom: verticalScale(20),
    borderRadius: scale(12),
    backgroundColor: colors.purple[200],
  },
  methodButton: {
    flex: 1,
    minHeight: verticalScale(42),
    borderRadius: scale(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scale(6),
  },
  activeMethodButton: {
    backgroundColor: colors.white[100],
    shadowColor: colors.black[250],
    shadowOffset: { width: scale(0), height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: scale(3),
    elevation: 2,
  },
  methodText: {
    fontFamily: fonts.SemiBold,
    color: colors.grey[700],
    fontSize: fontSize[13],
    fontWeight: '600',
  },
  activeMethodText: {
    color: colors.purple[700],
  },
  form: {
    gap: verticalScale(4),
  },
  submitButton: {
    height: verticalScale(48),
    marginTop: verticalScale(8),
  },
  buttonArrow: {
    fontFamily: fonts.Regular,
    color: colors.white[100],
    fontSize: fontSize[20],
  },
  successCard: {
    marginTop: verticalScale(20),
    padding: scale(16),
    borderRadius: scale(16),
    backgroundColor: colors.purple[100],
    borderWidth: scale(1),
    borderColor: colors.purple[300],
    alignItems: 'center',
    gap: verticalScale(10),
  },
  successIconBadge: {
    width: scale(48),
    height: scale(48),
    borderRadius: scale(24),
    backgroundColor: colors.purple[600],
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontFamily: fonts.Bold,
    color: colors.purple[800],
    fontSize: fontSize[17],
    fontWeight: '700',
    textAlign: 'center',
  },
  successDesc: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
    textAlign: 'center',
  },
  continueButton: {
    marginTop: verticalScale(6),
    height: verticalScale(44),
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: scale(6),
    paddingTop: verticalScale(28),
    paddingBottom: verticalScale(16),
  },
  footerText: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[14],
  },
  footerLink: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontSize: fontSize[14],
    fontWeight: '600',
  },
  highlightDestination: {
    fontFamily: fonts.Bold,
    fontWeight: '700',
    color: colors.purple[700],
  },
});
