import {
    StyleSheet,
} from "react-native"
import { colors, fonts, fontSize, scale, verticalScale } from "../../../constants";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.purple[50],
    },
    content: {
        flexGrow: 1,
        paddingHorizontal: scale(16),
        paddingBottom: verticalScale(28),
    },
    intro: {
        alignItems: 'center',
        paddingTop: verticalScale(24),
        paddingBottom: verticalScale(20),
    },
    logo: {
        width: scale(80),
        height: scale(80),
        borderRadius: scale(16),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.purple[200],
        marginBottom: verticalScale(16),
    },
    logoText: {
        fontFamily: fonts.Bold,
        color: colors.purple[700],
        fontSize: fontSize[44],
        fontWeight: '800',
        lineHeight: verticalScale(52),
    },
    logoAccent: {
        position: 'absolute',
        width: scale(8),
        height: verticalScale(8),
        borderRadius: scale(4),
        right: scale(18),
        top: verticalScale(18),
        backgroundColor: colors.purple[500],
    },
    verifiedPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
        borderRadius: scale(20),
        backgroundColor: colors.purple[300],
        marginBottom: verticalScale(8),
    },
    verifiedIcon: {
        fontFamily: fonts.Bold,
        color: colors.purple[800],
        fontSize: fontSize[14],
        fontWeight: '700',
    },
    verifiedText: {
        fontFamily: fonts.SemiBold,
        color: colors.purple[800],
        fontSize: fontSize[11],
        fontWeight: '600',
    },
    heading: {
        fontFamily: fonts.Bold,
        color: colors.black[250],
        fontSize: fontSize[26],
        lineHeight: verticalScale(34),
        fontWeight: '700',
        marginBottom: verticalScale(4),
    },
    subheading: {
        maxWidth: scale(280),
        fontFamily: fonts.Regular,
        color: colors.grey[700],
        fontSize: fontSize[14],
        lineHeight: verticalScale(20),
        textAlign: 'center',
    },
    options: {
        gap: scale(12),
        marginTop: verticalScale(4),
        marginBottom: verticalScale(24),
    },
    roleCard: {
        minHeight: verticalScale(112),
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(16),
        padding: scale(16),
        borderRadius: scale(16),
        backgroundColor: colors.white[100],
        shadowColor: colors.black[250],
        shadowOffset: { width: scale(0), height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: scale(6),
        elevation: 2,
    },
    selectedRoleCard: {
        backgroundColor: colors.purple[200],
        shadowOpacity: 0.1,
        elevation: 3,
    },
    pressedCard: {
        opacity: 0.85,
    },
    roleIcon: {
        width: scale(48),
        height: verticalScale(48),
        borderRadius: scale(12),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.purple[100],
    },
    selectedRoleIcon: {
        backgroundColor: colors.purple[600],
    },
    roleIconText: {
        fontFamily: fonts.Regular,
        color: colors.grey[700],
        fontSize: fontSize[28],
        lineHeight: verticalScale(32),
    },
    selectedRoleIconText: {
        color: colors.white[100],
    },
    roleCopy: {
        flex: 1,
        paddingRight: scale(20),
    },
    roleTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: scale(8),
        marginBottom: verticalScale(4),
    },
    roleTitle: {
        fontFamily: fonts.SemiBold,
        color: colors.black[250],
        fontSize: fontSize[16],
        lineHeight: verticalScale(22),
        fontWeight: '600',
    },
    badge: {
        fontFamily: fonts.SemiBold,
        color: colors.purple[800],
        backgroundColor: colors.purple[300],
        borderRadius: scale(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        fontSize: fontSize[11],
        lineHeight: verticalScale(14),
        fontWeight: '600',
    },
    roleDescription: {
        fontFamily: fonts.Regular,
        color: colors.grey[700],
        fontSize: fontSize[13],
        lineHeight: verticalScale(18),
    },
    radio: {
        position: 'absolute',
        top: verticalScale(16),
        right: scale(16),
        width: scale(24),
        height: verticalScale(24),
        borderRadius: scale(12),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.purple[400],
    },
    selectedRadio: {
        backgroundColor: colors.purple[700],
    },
    checkmark: {
        fontFamily: fonts.Bold,
        color: colors.white[100],
        fontSize: fontSize[16],
        fontWeight: '700',
    },
    radioDot: {
        fontFamily: fonts.Regular,
        color: colors.grey[700],
        fontSize: fontSize[18],
        lineHeight: verticalScale(20),
    },
    actions: {
        marginTop: 'auto',
        gap: scale(12),
    },
    continueButton: {
        height: verticalScale(48),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        borderRadius: scale(12),
        backgroundColor: colors.purple[600],
    },
    pressedButton: {
        opacity: 0.88,
    },
    continueText: {
        fontFamily: fonts.SemiBold,
        color: colors.white[100],
        fontSize: fontSize[14],
        lineHeight: verticalScale(20),
        fontWeight: '600',
    },
    arrow: {
        fontFamily: fonts.Regular,
        color: colors.white[100],
        fontSize: fontSize[20],
        lineHeight: verticalScale(20),
    },
    signInRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(6),
        paddingVertical: verticalScale(4),
    },
    signInPrompt: {
        fontFamily: fonts.Regular,
        color: colors.grey[700],
        fontSize: fontSize[14],
        lineHeight: verticalScale(20),
    },
    signInText: {
        fontFamily: fonts.SemiBold,
        color: colors.purple[700],
        fontSize: fontSize[14],
        lineHeight: verticalScale(20),
        fontWeight: '600',
    },
});