import { StyleSheet } from 'react-native';
import { colors, fonts, fontSize, scale, verticalScale } from '../../../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.purple[50],
  },
  header: {
    height: verticalScale(64),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    backgroundColor: colors.purple[50],
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.purple[200],
  },
  backButton: {
    width: scale(44),
    height: scale(44),
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    fontFamily: fonts.Regular,
    color: colors.black[250],
    fontSize: fontSize[34],
    lineHeight: verticalScale(36),
    fontWeight: '300',
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    flex: 1,
  },
  headerLogo: {
    width: scale(28),
    height: scale(28),
  },
  brandName: {
    fontFamily: fonts.Bold,
    color: colors.black[250],
    fontSize: fontSize[16],
    fontWeight: '700',
  },
  headerTitle: {
    maxWidth: scale(140),
    fontFamily: fonts.Medium,
    color: colors.grey[700],
    fontSize: fontSize[14],
    fontWeight: '500',
  },
  profileCircle: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[700],
  },
  profileIcon: {
    color: colors.white[100],
    fontSize: fontSize[12],
  },
  content: {
    flexGrow: 1,
    paddingBottom: verticalScale(24),
  },
  intro: {
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingTop: verticalScale(12),
    paddingBottom: verticalScale(16),
  },
  shield: {
    width: scale(64),
    height: scale(64),
    borderRadius: scale(32),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[300],
    marginBottom: verticalScale(14),
  },
  shieldIcon: {
    color: colors.purple[700],
    fontSize: fontSize[30],
  },
  lockBadge: {
    position: 'absolute',
    right: scale(-2),
    bottom: verticalScale(-2),
    width: scale(24),
    height: verticalScale(24),
    borderRadius: scale(12),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.purple[700],
  },
  lockIcon: {
    color: colors.white[100],
    fontSize: fontSize[12],
  },
  progress: {
    flexDirection: 'row',
    gap: scale(6),
    marginBottom: verticalScale(12),
  },
  progressActive: {
    width: scale(24),
    height: verticalScale(6),
    borderRadius: scale(3),
    backgroundColor: colors.purple[700],
  },
  progressInactive: {
    width: scale(8),
    height: verticalScale(6),
    borderRadius: scale(3),
    backgroundColor: colors.purple[400],
  },
  heading: {
    fontFamily: fonts.Bold,
    color: colors.black[250],
    fontSize: fontSize[26],
    lineHeight: verticalScale(34),
    fontWeight: '700',
    marginBottom: verticalScale(4),
  },
  instructions: {
    maxWidth: scale(280),
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[14],
    lineHeight: verticalScale(20),
    textAlign: 'center',
  },
  emailTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginTop: verticalScale(6),
    paddingHorizontal: scale(12),
    paddingVertical: verticalScale(5),
    borderRadius: scale(20),
    backgroundColor: colors.purple[100],
  },
  emailIcon: {
    color: colors.purple[700],
    fontSize: fontSize[15],
  },
  emailAddress: {
    fontFamily: fonts.SemiBold,
    color: colors.black[250],
    fontSize: fontSize[14],
    fontWeight: '600',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(2),
  },
  editText: {
    fontFamily: fonts.SemiBold,
    color: colors.purple[700],
    fontSize: fontSize[12],
    fontWeight: '600',
  },
  editIcon: {
    color: colors.purple[700],
    fontSize: fontSize[12],
  },
  otpSection: {
    alignItems: 'center',
    paddingHorizontal: scale(16),
  },
  errorText: {
    fontFamily: fonts.Regular,
    color: colors.red[200],
    fontSize: fontSize[12],
    lineHeight: verticalScale(16),
    alignSelf: 'flex-start',
    marginTop: verticalScale(6),
  },
  otpRow: {
    width: '100%',
    maxWidth: scale(360),
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: scale(4),
    marginVertical: verticalScale(8),
  },
  resendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    marginTop: verticalScale(8),
    marginBottom: verticalScale(16),
  },
  openMailHint: {
    textAlign: 'center',
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
    marginTop: verticalScale(10),
    marginBottom: verticalScale(2),
  },
  resendPrompt: {
    fontFamily: fonts.Regular,
    color: colors.grey[700],
    fontSize: fontSize[13],
    lineHeight: verticalScale(18),
  },
  countdown: {
    fontFamily: fonts.SemiBold,
    color: colors.grey[450],
    fontSize: fontSize[12],
    fontWeight: '600',
  },
  resendButton: {
    paddingVertical: verticalScale(4),
  },
  resendText: {
    fontFamily: fonts.Bold,
    color: colors.purple[700],
    fontSize: fontSize[12],
    fontWeight: '700',
  },
  trustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    marginTop: verticalScale(10),
  },
  trustIcon: {
    color: colors.grey[450],
    fontSize: fontSize[13],
  },
  trustText: {
    fontFamily: fonts.Regular,
    color: colors.grey[450],
    fontSize: fontSize[12],
  },
  buttonIcon: {
    color: colors.white[100],
    fontSize: fontSize[20],
  },
  verifyButton: {
    minHeight: verticalScale(48),
    borderRadius: scale(12),
  },
  verifyButtonText: {
    fontFamily: fonts.SemiBold,
    fontSize: fontSize[14],
  },
});
